import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/Designer4.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'
import TransitionsEffect from '@/components/TransitionsEffect'


export default function Home() {

  return (
    <>
      <Head>
        <title>Sahil Gutpa</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionsEffect />

      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>

        <Layout className='pt-0 md:pt-16 sm:pt-8'>

          <div className='flex items-center justify-between w-full lg:flex-col'>

            <div className='w-1/2 md:w-full p-14'>
              <Image src={profilePic} alt='Devloper'
                className='w-full h-auto lg:hidden md:inline-block md:w-full rounded-3xl'
                priority
                sizes="(max-width: 768px) 100vw,
                        (max-width: 1200px) 50vw,
                        50vw"
              />
            </div>

            <div className='w-1/2 flex flex-col items-center self-center lg:w-full  lg:text-center'>

              <AnimatedText
                text="Forging Digital Dreams: Where Vision Meets Innovation."
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl
                            md:!text-5xl sm:!text-3xl'
              />

              <p className='my-4 text-base font-medium md:text-sm sm:text-sm'>
                As a seasoned full-stack developer I turn visions to Virtual Reality.
                Building tomorrow&apos;s Web with React.JS, Next.JS and beyond. Discover my portfolio of innovation.
              </p>

              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/Sahil_Resume.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border-2 border-solid border-transparent hover:border-dark hover:duration-300
                  dark:bg-light dark:text-dark dark:border-light dark:hover:text-light dark:hover:bg-dark
                  md:p-2 md:px-4 md:text-base'
                  download={true}
                >
                  Resume <LinkArrow className='w-6 ml-1' />
                </Link>

                <Link href="mailto:sahilll03022003@gmail.com" target={"_blank"}
                  className='ml-8 text-lg font-medium capitalize text-dark underline dark:text-light
                             md:text-base'
                >
                  Contact
                </Link>
              </div>

            </div>

          </div>

        </Layout>

        <HireMe />

      </main>

    </>
  )
}